# This workflow will close PR's to main branch except release/* and hotfix/* branches

name: Close Pull Request

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  run:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/') != true && startsWith(github.head_ref, 'hotfix/') != true
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "We accept PR's to main only from release/* and hotfix/* branches"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
