# This workflow is triggered when a new release branch is created.

name: pre-release CI

on:
  create:

jobs:
  version:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap

      - name: Run tests # Run tests of all packages
        run: npm run test

      - run: git config --global user.name ${{github.actor}}
      - run: npm run version:pre-release -- --yes --amend
