# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pre-release CI

on:
  create:

jobs:
  version:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run prestart
      #- run: npm run build
      - run: npm run test
      - run: git config --global user.name ${{github.actor}}
      - run: npm run version:pre-release -y
