# This workflow is triggered when a new release branch is created.

name: pre-release CI

on:
  create:

jobs:
  version:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap
      - run: git config --global user.name ${{github.actor}}
      - run: npm run version:pre-release -- -y
