# This workflow will do a clean install of node dependencies, cache/restore them between runs, and run tests across different versions of node

name: Test changes CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap

      - name: Run tests # Run tests of all packages
        run: npx nx run-many -t test --passWithNoTests
