# This workflow is triggered when a pull request is opened against the main branch.

name: Update package versions CI

on:
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  version:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/install-and-test.yml
      - run: git config --global user.name ${{github.actor}}
      - run: npm run version:release -- --yes --amend
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
