# This workflow is triggered when a pull request is opened against the main branch.

name: Update package versions CI

on:
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  version:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
          fetch-depth: 0
      - run: git fetch --prune
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: npm
      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap
      - run: git config --global user.name ${{github.actor}}
      - run: npm run version:release -- -y
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
